CREATE SEQUENCE SEQ_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_USERS (
      USER_ID NUMBER PRIMARY KEY,
      NAME VARCHAR2(100) NOT NULL,
      EMAIL VARCHAR2(100) NOT NULL UNIQUE,
      PASSWORD VARCHAR2(255) NOT NULL,
      ROLE VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL
);