CREATE SEQUENCE SEQ_COLLECTIONS_POINTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_COLLECTIONS_POINTS (
    POINT_ID NUMBER PRIMARY KEY,
    NM_POINT VARCHAR2(100) NOT NULL,
    DS_LOCATION VARCHAR2(150) NOT NULL,
    MX_CAPACITY NUMBER NOT NULL
);