CREATE SEQUENCE SEQ_TYPE_RESIDUE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_TYPE_RESIDUE(
    TYPE_ID NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    RECYCLABLE CHAR(1) CHECK (RECYCLABLE IN ('Y','N'))
);