CREATE SEQUENCE SEQ_RESIDUE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_RESIDUE (
    RESIDUE_ID NUMBER PRIMARY KEY,
    POINT_ID NUMBER NOT NULL,
    TYPE_ID NUMBER NOT NULL,
    QTY_CURRENT NUMBER NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT FK_RESIDUE_POINT FOREIGN KEY (POINT_ID)
        REFERENCES TB_COLLECTIONS_POINTS (POINT_ID),

    CONSTRAINT FK_RESIDUE_TYPE FOREIGN KEY (TYPE_ID)
        REFERENCES TB_TYPE_RESIDUE (TYPE_ID)
);