CREATE SEQUENCE SEQ_COLLECTIONS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_COLLECTIONS (
    COLLECT_ID NUMBER PRIMARY KEY,
    RESIDUE_ID NUMBER NOT NULL,
    QTY_COLLECTED NUMBER NOT NULL,
    DT_COLLECTION DATE,
    DS_DESTINATION VARCHAR2(100),
    CONSTRAINT FK_COLLECT_RESIDUE FOREIGN KEY (RESIDUE_ID)
        REFERENCES TB_RESIDUE(RESIDUE_ID)
)