CREATE SEQUENCE SEQ_ALERTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    RESIDUE_ID NUMBER NOT NULL,
    TP_ALERT VARCHAR2(100),
    DS_MESSAGE VARCHAR2(250),
    DT_ALERT DATE,
    CONSTRAINT FK_ALERT_RESIDUE FOREIGN KEY (RESIDUE_ID)
        REFERENCES TB_RESIDUE (RESIDUE_ID)
)