ALTER TABLE TB_RESIDUE ADD (
    ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_RESIDUE_ACTIVE CHECK (ACTIVE IN ('Y','N'))
);

ALTER TABLE TB_COLLECTIONS ADD (
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE TB_ALERTS ADD (
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);
