-- Seed users (passwords: admin123 / operador123 / auditor123 — BCrypt hashed)
INSERT INTO TB_USERS (USER_ID, NAME, EMAIL, PASSWORD, ROLE)
VALUES (SEQ_USERS.NEXTVAL, 'Admin', 'admin@coletaplus.local',
        '$2y$10$YWsSanEOnqwqWdP72uKZZeyyz8jsya5jRbrQkW0L6AuHZXVUEAU5O',
        'ADMIN');

INSERT INTO TB_USERS (USER_ID, NAME, EMAIL, PASSWORD, ROLE)
VALUES (SEQ_USERS.NEXTVAL, 'Operador', 'operador@coletaplus.local',
        '$2y$10$ny4Z8O4ZVzPDNQLSDcBRbePQshYjL91xSOq8BQuaVOP2q2l/CmCny',
        'USER');

INSERT INTO TB_USERS (USER_ID, NAME, EMAIL, PASSWORD, ROLE)
VALUES (SEQ_USERS.NEXTVAL, 'Auditor', 'auditor@coletaplus.local',
        '$2y$10$wMCoBx8podI8.3obZqZfGe3k2f5fgc5g95uSQ3w4zJVxGzO84l2M.',
        'AUDIT');

-- Seed residue types
INSERT INTO TB_TYPE_RESIDUE (TYPE_ID, DESCRIPTION, RECYCLABLE)
VALUES (SEQ_TYPE_RESIDUE.NEXTVAL, 'Plastico', 'Y');

INSERT INTO TB_TYPE_RESIDUE (TYPE_ID, DESCRIPTION, RECYCLABLE)
VALUES (SEQ_TYPE_RESIDUE.NEXTVAL, 'Papel', 'Y');

INSERT INTO TB_TYPE_RESIDUE (TYPE_ID, DESCRIPTION, RECYCLABLE)
VALUES (SEQ_TYPE_RESIDUE.NEXTVAL, 'Organico', 'N');

-- Seed collection points
INSERT INTO TB_COLLECTIONS_POINTS (POINT_ID, NM_POINT, DS_LOCATION, MX_CAPACITY)
VALUES (SEQ_COLLECTIONS_POINTS.NEXTVAL, 'Ponto Central', 'Av. Paulista, 1000', 1000);

INSERT INTO TB_COLLECTIONS_POINTS (POINT_ID, NM_POINT, DS_LOCATION, MX_CAPACITY)
VALUES (SEQ_COLLECTIONS_POINTS.NEXTVAL, 'Ponto Zona Sul', 'Rua Vergueiro, 500', 500);
